### ISSUE TITLE
DST uses a loosely synchronized clock as the physical part

### ISSUE THREAD

**Issue by ChenyuGao** [SJTU-IPADS/dst#1]
我看到论文中有这一句，请问下是用的什么时钟同步算法呢，如何保证在网络负载较大时依然保证ms内的同步精度呢

**Comment by ChenyuGao** [comment]
另外，有关Bounded staleness的理解，是不是说在物理时钟同步的精度范围内，会出现实际发生较晚的事务T2不能读取到实际较早发生的事务T1的数据，因为有可能T1的提交时间戳比T2的读快照还要大

**Comment by wxdwfc** [comment]
第一个问题：DST使用ntp来同步时间，并不使用额外的机制保证同步精度。DST无需确保时间的精度，因为精度不影响正确性。
第二个问题，是的，T2不一定会读到T1的数据，所以DST只保证了serializability，不是strict serializability。

**Comment by ChenyuGao** [comment]
感谢回复，我也在做高精度时钟同步算法，当跑tpcc时，由于网络负载增大，会导致链路时延不对称从而引起同步精度降低，ntp本身是ms级的同步算法，受影响会更大，在这个论文中，会不会引起Bounded staleness更严重，有没有数据不一致问题呀？
另外没有考虑像spanner那样加上commit wait么

**Comment by wxdwfc** [comment]
“在这个论文中，会不会引起Bounded staleness更严重，有没有数据不一致问题呀？” Bounded staleness只涉及freshness，不影响correctness。因此，DST不会因为时钟不一致（或同步精度）导致数据不一致。基于同样的原因，DST不需要加上commit wait。详细可以参考我们的论文和DST的正确性说明。
ps：DST可以利用commit wait来提升freshness，但是这是这和DST本身的设计是正交的。

**Comment by ChenyuGao** [comment]
我看3.3正确性证明中的LEMMA 1，如果TX2依赖TX1，则TS2＞TS1。正常情况是这样，但会不会有这样的情况呢：节点1和节点2分别运行TX1和TX2，TX2依赖TX1，但由于时钟频率误差，节点1的时间总是比节点2要快，那虽然现实时间中TX1的提交时间会更小，但由于没有commit wait，在机器中读取到的TS1却比TS2大

**Comment by ChenyuGao** [comment]
> 我看3.3正确性证明中的LEMMA 1，如果TX2依赖TX1，则TS2＞TS1。正常情况是这样，但会不会有这样的情况呢：节点1和节点2分别运行TX1和TX2，TX2依赖TX1，但由于时钟频率误差，节点1的时间总是比节点2要快，那虽然现实时间中TX1的提交时间会更小，但由于没有commit wait，在机器中读取到的TS1却比TS2大

奥我看到在图7的WRITE函数中有一个取max的过程，所以上述情况下，应该是TX1和TX2的提交时间戳就相等了？

**Comment by ChenyuGao** [comment]
还有个问题请教一下，我可能没有理解好，DST跟混合逻辑时钟HLC的主要区别是什么呢

**Comment by wxdwfc** [comment]
DST使用HLC来确保freshness，所以和HLC是正交的关系，即DST不使用HLC也能正常工作。ps：论文相关的问题还是用邮件和我交流吧，谢谢。我的邮箱是wxdwfc at sjtu.edu.cn。
